### ISSUE TITLE
Request: text justification & transparency

### ISSUE THREAD

**Issue by warcayac** [JunoNgx/kde-currently-playing#1]
First off, this is a good widget, thanks. My request for improving it when it is on desktop:

1. Text justification,
2. Transparency,
3. Break info into two lines,
4. Change font family,
5. Text color.

Other widgets like NowPlaying have these features BUT they don't work so well with media controls and keyboards because they run an media operation twice (i.e. I click pause from keyboard, it is executed twice).

**Comment by JunoNgx** [comment]
Hi @warcayac,

This widget aims to be minimal and simple. While your suggestions are definitely useful for a lot of people, they are not essential or hold high priorities. Nevertheless, I would keep this issue open for interest checks from other users. I would consider implementing these if there are high demands for them.

Thank you for your feedback and suggestions.
